const sections=[
["Quem somos?",<>FGN Arquitetura e Participações LTDA<br/>CNPJ: 66.978.735/0001-00<br/>Endereço: Rua Florêncio de Abreu – Conj. 903 – Centro – Ribeirão Preto/SP.<br/>www.fgnarquitetura.com.br<br/><br/>Nós da FGN Arquitetura estamos empenhados em proteger os dados pessoais dos nossos clientes e utilizadores do website, em todas as situações em que ocorra o fornecimento desses dados. Esta Política expressa nosso compromisso com as regras de proteção de dados pessoais.</>],
["Por que existe a Política de Privacidade?",<>Esta Política informa aos nossos clientes e utilizadores as regras gerais de privacidade e tratamento dos seus dados pessoais, tratados com o máximo respeito e em cumprimento à Lei Geral de Proteção de Dados Pessoais. A disponibilização de dados pessoais em nosso site implica conhecimento e aceitação destas condições.</>],
["O que abrange esta Política de Privacidade?",<>Esta Política aplica-se exclusivamente à coleta e ao tratamento de dados pessoais efetuados pela FGN Arquitetura. Links para outros websites são disponibilizados de boa-fé; recomendamos a leitura da política de privacidade de cada site visitado.</>],
["O que são dados pessoais?",<>Dados pessoais são quaisquer informações relativas a uma pessoa identificada ou identificável, direta ou indiretamente, incluindo elementos de sua identidade física, fisiológica, psíquica, econômica, cultural ou social.</>],
["Quem é o responsável pelo tratamento de dados?",<>A entidade responsável pela coleta e tratamento dos dados pessoais é a FGN Arquitetura, que decide quais dados são coletados, os meios de tratamento e as finalidades de utilização.</>],
["Que tipo de dados pessoais recolhemos?",<>No âmbito de sua atividade, a FGN Arquitetura coleta os dados necessários à prestação dos serviços, como nome, endereço, número de telefone e e-mail.</>],
["Quando e como recolhemos os seus dados?",<>Coletamos dados por telefone, por escrito ou através do website, mediante consentimento. Os dados são tratados informaticamente, em estrito cumprimento da legislação, e utilizados somente para a finalidade informada ao titular.</>],
["Quais as finalidades do tratamento?",<>Os dados podem ser utilizados para emissão de orçamentos, comunicações, atendimento de reclamações e sugestões, informações institucionais, campanhas e pesquisas de avaliação. Informações detalhadas serão apresentadas no momento da coleta.</>],
["Por quanto tempo conservamos os dados?",<>Os dados são armazenados apenas pelo período mínimo necessário às finalidades que motivaram sua coleta ou pelo prazo exigido em lei, sendo eliminados ao final desse período.</>],
["Como acessar, retificar ou eliminar seus dados?",<>Nos termos da LGPD, o titular pode solicitar acesso, atualização, retificação ou eliminação de seus dados pelo e-mail comercial@fgnarquitetura.com.br.</>],
["Contatos para fins de marketing",<>Caso não pretenda mais receber comunicações, solicite a exclusão da lista pelo e-mail comercial@fgnarquitetura.com.br.</>],
["Segurança dos dados pessoais",<>A FGN Arquitetura adota medidas técnicas e organizacionais para proteger os dados contra difusão, perda, uso indevido, alteração, tratamento ou acesso não autorizado. Recomendamos também que os usuários mantenham dispositivos, navegadores, antivírus e firewall atualizados.</>],
["Comunicação de dados a terceiros",<>A FGN Arquitetura poderá recorrer a terceiros para a prestação de serviços. Quando houver acesso a dados pessoais, serão exigidas medidas técnicas, organizacionais e contratuais adequadas, permanecendo a FGN responsável pelos dados disponibilizados.</>],
["Como usamos cookies?",<>Cookies são pequenas etiquetas de software armazenadas pelo navegador, com informações relacionadas às preferências do usuário, sem incluir dados pessoais.</>],
["Alterações desta Política",<>A FGN Arquitetura reserva-se o direito de ajustar esta Política a qualquer momento, publicando as alterações neste website.</>]
];
export default function Privacy(){return <main className="privacy"><header><a href="/"><img src="/images/logo.png" alt="FGN Arquitetura"/></a><a href="/">Voltar ao site</a></header><article><p className="eyebrow">FGN Arquitetura</p><h1>Política de privacidade</h1>{sections.map(([title,body])=><section key={String(title)}><h2>{title}</h2><p>{body}</p></section>)}</article></main>}
