"use client";
import { useEffect, useState } from "react";

const services = [["Parcelamento do Solo","\ue907"],["Estudo de Massa","\ue903"],["Estudo Preliminar","\ue905"],["Projeto Arquitetônico","\ue901"],["Projeto Legal (ou Projeto de Prefeitura)","\ue906"],["Compatibilização de Projetos Complementares","\ue902"],["Projeto Executivo","\ue904"],["Projeto de Acessibilidade","\ue900"]];
const projects = [["Tomoichi","capa-proj-tomoichi.png"],["André de Almeida","capa-proj-andre-1.png"],["Santa Ângela","capa-proj-santaangela.png"],["Santa Beatriz","capa-proj-santabeatriz.png"],["Santa Amélia","capa-proj-santaamelia.png"],["San Isidoro","capa-proj-sanluigi.png"],["San Luigi","capa-proj-sanluigi.png"],["San Patrick","capa-proj-patric.png"],["Golden Plaza","capa-proj-golden.png"],["Bicicletário Maria Augusta","capa-proj-bicicletario.jpg"],["Fitness Portes du Soleil","capa-proj-fitness.jpg"],["Santa Lúcia","capa-proj-santalucia.png"]];
const whats="https://api.whatsapp.com/send?phone=5516997475507&text=Olá%2C%20gostaria%20de%20solicitar%20um%20orçamento.";

export default function Home(){const[menu,setMenu]=useState(false);const[slide,setSlide]=useState(0);const[hero,setHero]=useState(0);const[paused,setPaused]=useState(false);useEffect(()=>{const t=setInterval(()=>setHero(v=>(v+1)%3),5000);return()=>clearInterval(t)},[]);useEffect(()=>{if(paused)return;const t=setInterval(()=>{const el=document.querySelector('.projectGrid');if(!el)return;const atEnd=el.scrollLeft+el.clientWidth>=el.scrollWidth-10;if(atEnd){el.scrollTo({left:0,behavior:'smooth'});setSlide(0)}else{el.scrollBy({left:el.clientWidth/5,behavior:'smooth'});setSlide(v=>Math.min(projects.length-1,v+1))}},3500);return()=>clearInterval(t)},[paused]);const move=(dir:number)=>{const el=document.querySelector('.projectGrid');if(el)el.scrollBy({left:dir*(el.clientWidth/5),behavior:'smooth'});setSlide(v=>Math.max(0,Math.min(projects.length-1,v+dir)))};return <main>
 <header className="header"><a href="#inicio"><img src="/images/logobranco.png" className="logo" alt="FGN Arquitetura Técnica BIM"/></a><div className="headerRight"><nav className={menu?"nav open":"nav"}>{[["sobre","Sobre a FGN"],["servicos","Serviços"],["projetos","Projetos"],["contato","Contato"]].map(x=><a key={x[0]} href={`#${x[0]}`} onClick={()=>setMenu(false)}>{x[1]}</a>)}</nav><div className="headerSocial"><a href="https://www.facebook.com/fgn.arquitetura/" target="_blank" rel="noreferrer" aria-label="Facebook">&#xf09a;</a><a href="https://www.linkedin.com/company/fgnarquitetura" target="_blank" rel="noreferrer" aria-label="LinkedIn">&#xf08c;</a><a href="https://www.instagram.com/fgn.arquitetura" target="_blank" rel="noreferrer" aria-label="Instagram">&#xf16d;</a></div></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menu"><span/><span/></button></header>
 <section className="hero" id="inicio"><div className={`heroBg hero${hero+1}`}/><div className="heroContent"><p className="eyebrow light">Há mais de uma década desenvolvendo projetos de alto desempenho</p><h1>Excelência em arquitetura para o mercado B2B</h1><div className="actions"><a className="button" href={whats} target="_blank">Solicitar orçamento</a></div></div><div className="heroDots">{[0,1,2].map(i=><button key={i} className={i===hero?'active':''} onClick={()=>setHero(i)} aria-label={`Banner ${i+1}`}/>)}</div></section>
 <section className="about wrap" id="sobre"><div className="aboutVisual"><img className="aboutOne" src="/images/foto-quem01.png" alt="Empreendimento projetado pela FGN"/><img className="aboutTwo" src="/images/foto-quem02.png" alt="Detalhe arquitetônico"/><div className="bimTag">Projetos<strong>em BIM</strong></div></div><div className="aboutText"><p className="eyebrow">Quem nós somos</p><h2>Sua parceira nacional em projetos de arquitetura.</h2><p className="intro">Atendemos construtoras, incorporadoras e escritórios de arquitetura em todo o Brasil.</p><p>Transformamos visões em soluções técnicas consistentes. Unimos domínio de legislação, planejamento, detalhamento e tecnologia BIM para estabelecer parcerias duradouras e construir empreendimentos de destaque.</p><a className="arrowLink" href={whats} target="_blank">Vamos conversar <span>→</span></a></div></section>
 <section className="numbers"><div className="wrap stats"><div><strong>+1 mi</strong><span>m² projetados</span></div><div><strong>+100</strong><span>empreendimentos</span></div><div><strong>+10</strong><span>anos de experiência</span></div></div></section>
 <section className="services wrap" id="servicos"><div className="sectionHead"><div><p className="eyebrow">O que nós fazemos</p><h2>Serviços</h2></div><p>Os serviços de arquitetura envolvem uma ampla gama de atividades relacionadas ao design, planejamento e construção de espaços arquitetônicos.</p></div><div className="serviceGrid">{services.map(([s,icon])=><article className="service" key={s}><span className="serviceIcon" aria-hidden="true">{icon}</span><h3>{s}</h3><a href="#contato">→ &nbsp;SAIBA MAIS</a></article>)}</div></section>
 <section className="projects" id="projetos" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)}><div className="wrap"><div className="projectGrid" tabIndex={0} aria-label="Carrossel de projetos em reprodução automática">{projects.map((p,i)=><article className="project" key={p[0]}><img src={`/images/${p[1]}`} alt={`Projeto ${p[0]}`} loading={i>4?"lazy":undefined}/><div><h3>{p[0]}</h3></div></article>)}</div><div className="carouselControls"><button onClick={()=>move(-1)} disabled={slide===0} aria-label="Projetos anteriores">←</button><span>{String(slide+1).padStart(2,'0')} / {projects.length}</span><button onClick={()=>move(1)} disabled={slide===projects.length-1} aria-label="Próximos projetos">→</button></div></div></section>
 <section className="trust wrap"><p className="eyebrow">Empresas que confiam na FGN</p><div className="clientLogos">{[1,2,3,4,5,6,7].map(n=><img src={`/images/logo-cliente0${n}-1.png`} key={n} alt="Cliente FGN"/>)}<img src="/images/logo-cliente09.png" alt="Cliente FGN"/></div></section>
 <section className="testimonials"><div className="wrap"><p className="eyebrow light">Depoimentos</p><div className="quotes"><blockquote>“Giselle é uma excelente profissional, extremamente comprometida, com capacidade em planejamento, detalhamento e uma constante busca de atualização dos conceitos e legislações.”<footer><strong>Michelle Alves</strong><span>DanPris Construtora</span></footer></blockquote><blockquote>“Confiança no prazo e no resultado é o que nos fazem tão fãs do trabalho da FGN. A equipe sempre nos atendeu prontamente em nossos maiores desafios de projeto.”<footer><strong>Cecília H. Figueiredo</strong><span>MRV Engenharia</span></footer></blockquote></div></div></section>
 <footer className="footer" id="contato"><div className="wrap footerTop"><img src="/images/logobranco.png" alt="FGN Arquitetura"/><h2>Vamos trabalhar juntos</h2><strong>Deixe-nos saber o que você precisa.</strong><p>Vamos formatar a solução que melhor lhe atenda.</p><strong>Rua Florêncio de Abreu, 681, cj. 903. Ed. Canadá. Ribeirão Preto/SP. CEP 14015-901.</strong><div className="footerContact"><a className="waCircle" href={whats} target="_blank" aria-label="WhatsApp">◉</a><a href="mailto:comercial@fgnarquitetura.com.br">comercial@fgnarquitetura.com.br</a></div></div><div className="wrap bottom"><div><span>2026 © FGN Arquitetura e Tecnologia Ltda. Todos os direitos reservados.</span><a href="/politica-de-privacidade">Política de privacidade</a></div><div className="footerSocial"><a href="https://www.facebook.com/fgn.arquitetura/" target="_blank" aria-label="Facebook">&#xf09a;</a><a href="https://www.linkedin.com/company/fgnarquitetura" target="_blank" aria-label="LinkedIn">&#xf08c;</a><a href="https://www.instagram.com/fgn.arquitetura" target="_blank" aria-label="Instagram">&#xf16d;</a></div></div></footer><a className="whatsapp" href={whats} target="_blank" aria-label="WhatsApp">WA</a>
 </main>}
