"use client";
import { useState } from "react";

const services = ["Parcelamento do Solo","Estudo de Massa","Estudo Preliminar","Projeto Arquitetônico","Projeto Legal","Compatibilização de Projetos","Projeto Executivo","Projeto de Acessibilidade"];
const projects = [["Tomoichi","capa-proj-tomoichi.png"],["André de Almeida","capa-proj-andre-1.png"],["Santa Ângela","capa-proj-santaangela.png"],["Santa Beatriz","capa-proj-santabeatriz.png"],["Santa Amélia","capa-proj-santaamelia.png"],["San Isidoro","capa-proj-sanluigi.png"],["San Luigi","capa-proj-sanluigi.png"],["San Patrick","capa-proj-patric.png"],["Golden Plaza","capa-proj-golden.png"],["Bicicletário Maria Augusta","capa-proj-bicicletario.jpg"],["Fitness Portes du Soleil","capa-proj-fitness.jpg"],["Santa Lúcia","capa-proj-santalucia.png"]];
const whats="https://api.whatsapp.com/send?phone=5516997475507&text=Olá%2C%20gostaria%20de%20solicitar%20um%20orçamento.";

export default function Home(){const[menu,setMenu]=useState(false);const[all,setAll]=useState(false);return <main>
 <header className="header"><a href="#inicio"><img src="/images/logo.png" className="logo" alt="FGN Arquitetura Técnica BIM"/></a><nav className={menu?"nav open":"nav"}>{[["sobre","Sobre a FGN"],["servicos","Serviços"],["projetos","Projetos"],["contato","Contato"]].map(x=><a key={x[0]} href={`#${x[0]}`} onClick={()=>setMenu(false)}>{x[1]}</a>)}</nav><a className="headerCta" href={whats} target="_blank">Solicitar orçamento</a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menu"><span/><span/></button></header>
 <section className="hero" id="inicio"><div className="heroBg"/><div className="heroContent"><p className="eyebrow light">Arquitetura técnica • BIM • atuação nacional</p><h1>Excelência em arquitetura para o mercado B2B</h1><p className="lead">Há mais de uma década desenvolvendo projetos de alto desempenho para construtoras, incorporadoras e escritórios de arquitetura.</p><div className="actions"><a className="button" href={whats} target="_blank">Solicitar orçamento <span>↗</span></a><a className="textLink" href="#projetos">Conheça nossos projetos ↓</a></div></div><div className="heroIndex">01 <span>/ 03</span></div></section>
 <section className="about wrap" id="sobre"><div className="aboutVisual"><img className="aboutOne" src="/images/foto-quem01.png" alt="Empreendimento projetado pela FGN"/><img className="aboutTwo" src="/images/foto-quem02.png" alt="Detalhe arquitetônico"/><div className="bimTag">Projetos<strong>em BIM</strong></div></div><div className="aboutText"><p className="eyebrow">Quem nós somos</p><h2>Sua parceira nacional em projetos de arquitetura.</h2><p className="intro">Atendemos construtoras, incorporadoras e escritórios de arquitetura em todo o Brasil.</p><p>Transformamos visões em soluções técnicas consistentes. Unimos domínio de legislação, planejamento, detalhamento e tecnologia BIM para estabelecer parcerias duradouras e construir empreendimentos de destaque.</p><a className="arrowLink" href={whats} target="_blank">Vamos conversar <span>→</span></a></div></section>
 <section className="numbers"><div className="wrap stats"><div><strong>+1 mi</strong><span>m² projetados</span></div><div><strong>+100</strong><span>empreendimentos</span></div><div><strong>+10</strong><span>anos de experiência</span></div></div></section>
 <section className="services wrap" id="servicos"><div className="sectionHead"><div><p className="eyebrow">O que nós fazemos</p><h2>Serviços</h2></div><p>Arquitetura técnica de ponta a ponta, com decisões precisas em cada fase do empreendimento.</p></div><div className="serviceGrid">{services.map((s,i)=><article className="service" key={s}><span>0{i+1}</span><h3>{s}</h3><p>Soluções técnicas eficientes, integradas e alinhadas às necessidades do empreendimento.</p><a href="#contato">Saiba mais →</a></article>)}</div></section>
 <section className="projects" id="projetos"><div className="wrap"><div className="sectionHead inverse"><div><p className="eyebrow light">Portfólio selecionado</p><h2>Projetos que transformam cidades</h2></div><p>Empreendimentos residenciais, comerciais e urbanos concebidos com precisão e visão de futuro.</p></div><div className="projectGrid">{projects.slice(0,all?12:6).map((p,i)=><article className="project" key={p[0]}><img src={`/images/${p[1]}`} alt={`Projeto ${p[0]}`} loading={i>2?"lazy":undefined}/><div><span>0{i+1}</span><h3>{p[0]}</h3><p>Arquitetura • Projeto técnico • BIM</p></div></article>)}</div>{!all&&<button className="more" onClick={()=>setAll(true)}>Ver mais projetos +</button>}</div></section>
 <section className="trust wrap"><p className="eyebrow">Empresas que confiam na FGN</p><div className="clientLogos">{[1,2,3,4,5,6,7].map(n=><img src={`/images/logo-cliente0${n}-1.png`} key={n} alt="Cliente FGN"/>)}<img src="/images/logo-cliente09.png" alt="Cliente FGN"/></div></section>
 <section className="testimonials"><div className="wrap"><p className="eyebrow light">Depoimentos</p><div className="quotes"><blockquote>“Giselle é uma excelente profissional, extremamente comprometida, com capacidade em planejamento, detalhamento e uma constante busca de atualização dos conceitos e legislações.”<footer><strong>Michelle Alves</strong><span>DanPris Construtora</span></footer></blockquote><blockquote>“Confiança no prazo e no resultado é o que nos fazem tão fãs do trabalho da FGN. A equipe sempre nos atendeu prontamente em nossos maiores desafios de projeto.”<footer><strong>Cecília H. Figueiredo</strong><span>MRV Engenharia</span></footer></blockquote></div></div></section>
 <footer className="footer" id="contato"><div className="wrap footerGrid"><div><img src="/images/logobranco.png" alt="FGN Arquitetura"/><p>Vamos trabalhar juntos.</p><h2>Conte o que você precisa. Nós formatamos a melhor solução.</h2><a className="button" href={whats} target="_blank">Solicitar orçamento <span>↗</span></a></div><div className="contact"><p className="eyebrow light">Contato</p><a href="mailto:comercial@fgnarquitetura.com.br">comercial@fgnarquitetura.com.br</a><p>Rua Florêncio de Abreu, 681, cj. 903<br/>Ed. Canadá — Ribeirão Preto/SP<br/>CEP 14015-901</p><div className="social"><a href="https://www.instagram.com/fgnarquitetura/" target="_blank">Instagram</a><a href="https://www.linkedin.com/company/fgn-arquitetura/" target="_blank">LinkedIn</a></div></div></div><div className="wrap bottom"><span>© 2026 FGN Arquitetura Técnica BIM</span><a href="#">Política de privacidade</a></div></footer><a className="whatsapp" href={whats} target="_blank" aria-label="WhatsApp">WA</a>
 </main>}
