backend:
  name: github
  repo: helbioads/fgn-arquitetura
  branch: main
  site_domain: fgnarquitetura.com.br

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Conteúdo"
    delete: false
    editor:
      preview: false
    files:
      - name: "depoimentos"
        label: "Depoimentos"
        file: "content/testimonials.json"
        fields:
          - label: "Lista de Depoimentos"
            name: "testimonials"
            widget: "list"
            summary: "{{fields.author}} ({{fields.company}})"
            fields:
              - { label: "Autor", name: "author", widget: "string" }
              - { label: "Empresa / Construtora", name: "company", widget: "string" }
              - { label: "Depoimento", name: "quote", widget: "text" }
      - name: "projetos"
        label: "Projetos (Portfólio)"
        file: "content/projects.json"
        fields:
          - label: "Lista de Projetos"
            name: "projects"
            widget: "list"
            summary: "{{fields.title}} ({{fields.slug}})"
            fields:
              - { label: "Título do Projeto", name: "title", widget: "string" }
              - { label: "Slug da URL", name: "slug", widget: "string" }
              - { label: "Capa do Projeto", name: "cover", widget: "image" }
              - label: "Galeria de Imagens", name: "images", widget: "list", field: { label: "Imagem", widget: "image" }
