"use client";
import {useEffect,useState} from "react";
const data=[
["Parcelamento do Solo","\ue907",["O parcelamento do solo é um processo que consiste em parcelar ou dividir um terreno ou gleba em lotes menores. Esse processo pode ser na forma de loteamento, desmembramento e fracionamento, sempre mediante aprovação dos órgãos públicos."]],
["Estudo de Massa","\ue903",["O estudo de massa leva em conta o potencial construtivo do local, traduzindo em projeto a legislação aplicável, como recuos mínimos, gabarito, áreas permeáveis e outros índices.","Também considera topografia, limitações ambientais, diretrizes viárias e servidões, ajudando a estabelecer a melhor forma de ocupação do empreendimento."]],
["Estudo Preliminar","\ue905",["O estudo preliminar apresenta a proposta de solução arquitetônica, com análise do terreno, níveis, acessos, áreas permeáveis, estacionamento e quadro de índices preliminares.","É fundamental que esta etapa já atenda à legislação vigente e às diretrizes estabelecidas para o lote."]],
["Projeto Arquitetônico","\ue901",["O projeto arquitetônico compreende a montagem e o desenvolvimento do material conforme a proposta discutida no estudo preliminar.","Inclui plantas, cortes e fachadas em escala adequada, suficientes para o completo entendimento do projeto."]],
["Projeto Legal (ou Projeto de Prefeitura)","\ue906",["O projeto legal adapta a representação do projeto arquitetônico às exigências das prefeituras municipais.","Pode incluir a vinculação de vagas às unidades habitacionais para posterior registro, conforme interesse da construtora ou exigência do município."]],
["Compatibilização de Projetos Complementares","\ue902",["A compatibilização integra o projeto arquitetônico aos projetos de engenharia — estrutural, elétrica, hidráulica, ar-condicionado, gases medicinais e outros — garantindo o funcionamento conjunto e a qualidade arquitetônica."]],
["Projeto Executivo","\ue904",["É a representação detalhada do projeto, suficiente para a execução da obra. Pode incluir esquadrias, acabamentos, paginação de pisos, paredes, tetos e áreas molhadas."]],
["Projeto de Acessibilidade","\ue900",["Consiste em adequar acessos, circulações, mobiliário e espaços à legislação vigente, como a NBR 9050/2020.","Especifica pisos de alerta e direcionais, guias de balizamento, corrimãos e guarda-corpos."]]
];
export default function Services(){const[active,setActive]=useState(0);useEffect(()=>{const n=Math.max(0,Number(location.hash.replace('#sessao',''))-1);if(n<8)setActive(n)},[]);return <main className="servicePage"><header><a href="/"><img src="/images/logo.png" alt="FGN Arquitetura"/></a><a href="/">Voltar ao site</a></header><section className="serviceIntro"><p>Conheça</p><h1>Serviços</h1><span>A FGN oferece uma ampla gama de serviços de arquitetura. <strong>Confira!</strong></span></section><section className="serviceTabs"><nav>{data.map((d,i)=><button key={d[0]} className={active===i?'active':''} onClick={()=>{setActive(i);history.replaceState(null,'',`#sessao0${i+1}`)}}><i>{d[1]}</i><span>{d[0]}</span></button>)}</nav><article id={`sessao0${active+1}`}><i>{data[active][1]}</i><h2>{data[active][0]}</h2>{(data[active][2] as string[]).map(p=><p key={p}>{p}</p>)}</article></section></main>}
